// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.19.6
// source: biloba/v1/driver.proto

package bilobav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocatorKind int32

const (
	LocatorKind_LOCATOR_KIND_UNSPECIFIED LocatorKind = 0
	LocatorKind_CSS                      LocatorKind = 1
	LocatorKind_TEST_ID                  LocatorKind = 2
	LocatorKind_TEXT                     LocatorKind = 3
	LocatorKind_ROLE                     LocatorKind = 4
)

// Enum value maps for LocatorKind.
var (
	LocatorKind_name = map[int32]string{
		0: "LOCATOR_KIND_UNSPECIFIED",
		1: "CSS",
		2: "TEST_ID",
		3: "TEXT",
		4: "ROLE",
	}
	LocatorKind_value = map[string]int32{
		"LOCATOR_KIND_UNSPECIFIED": 0,
		"CSS":                      1,
		"TEST_ID":                  2,
		"TEXT":                     3,
		"ROLE":                     4,
	}
)

func (x LocatorKind) Enum() *LocatorKind {
	p := new(LocatorKind)
	*p = x
	return p
}

func (x LocatorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocatorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_biloba_v1_driver_proto_enumTypes[0].Descriptor()
}

func (LocatorKind) Type() protoreflect.EnumType {
	return &file_biloba_v1_driver_proto_enumTypes[0]
}

func (x LocatorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocatorKind.Descriptor instead.
func (LocatorKind) EnumDescriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{0}
}

type MatchMode int32

const (
	MatchMode_MATCH_MODE_UNSPECIFIED MatchMode = 0
	MatchMode_EXACT                  MatchMode = 1
	MatchMode_CONTAINS               MatchMode = 2
)

// Enum value maps for MatchMode.
var (
	MatchMode_name = map[int32]string{
		0: "MATCH_MODE_UNSPECIFIED",
		1: "EXACT",
		2: "CONTAINS",
	}
	MatchMode_value = map[string]int32{
		"MATCH_MODE_UNSPECIFIED": 0,
		"EXACT":                  1,
		"CONTAINS":               2,
	}
)

func (x MatchMode) Enum() *MatchMode {
	p := new(MatchMode)
	*p = x
	return p
}

func (x MatchMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchMode) Descriptor() protoreflect.EnumDescriptor {
	return file_biloba_v1_driver_proto_enumTypes[1].Descriptor()
}

func (MatchMode) Type() protoreflect.EnumType {
	return &file_biloba_v1_driver_proto_enumTypes[1]
}

func (x MatchMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchMode.Descriptor instead.
func (MatchMode) EnumDescriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{1}
}

type Assertion_Kind int32

const (
	Assertion_KIND_UNSPECIFIED Assertion_Kind = 0
	Assertion_VISIBLE          Assertion_Kind = 1
	Assertion_TEXT             Assertion_Kind = 2
	Assertion_COUNT            Assertion_Kind = 3
	Assertion_ATTRIBUTE        Assertion_Kind = 4
	Assertion_VALUE            Assertion_Kind = 5
	Assertion_URL              Assertion_Kind = 6
	Assertion_EVALUATE         Assertion_Kind = 7
)

// Enum value maps for Assertion_Kind.
var (
	Assertion_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "VISIBLE",
		2: "TEXT",
		3: "COUNT",
		4: "ATTRIBUTE",
		5: "VALUE",
		6: "URL",
		7: "EVALUATE",
	}
	Assertion_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"VISIBLE":          1,
		"TEXT":             2,
		"COUNT":            3,
		"ATTRIBUTE":        4,
		"VALUE":            5,
		"URL":              6,
		"EVALUATE":         7,
	}
)

func (x Assertion_Kind) Enum() *Assertion_Kind {
	p := new(Assertion_Kind)
	*p = x
	return p
}

func (x Assertion_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Assertion_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_biloba_v1_driver_proto_enumTypes[2].Descriptor()
}

func (Assertion_Kind) Type() protoreflect.EnumType {
	return &file_biloba_v1_driver_proto_enumTypes[2]
}

func (x Assertion_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Assertion_Kind.Descriptor instead.
func (Assertion_Kind) EnumDescriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{15, 0}
}

type HandshakeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_biloba_v1_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_biloba_v1_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{1}
}

type HandshakeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_biloba_v1_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HandshakeResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type OpenSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_biloba_v1_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{3}
}

type OpenSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionResponse) Reset() {
	*x = OpenSessionResponse{}
	mi := &file_biloba_v1_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionResponse) ProtoMessage() {}

func (x *OpenSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionResponse.ProtoReflect.Descriptor instead.
func (*OpenSessionResponse) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{4}
}

func (x *OpenSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PrepareSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareSessionRequest) Reset() {
	*x = PrepareSessionRequest{}
	mi := &file_biloba_v1_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareSessionRequest) ProtoMessage() {}

func (x *PrepareSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareSessionRequest.ProtoReflect.Descriptor instead.
func (*PrepareSessionRequest) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{5}
}

func (x *PrepareSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_biloba_v1_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{6}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Locator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          LocatorKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=biloba.v1.LocatorKind" json:"kind,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Match         MatchMode              `protobuf:"varint,5,opt,name=match,proto3,enum=biloba.v1.MatchMode" json:"match,omitempty"`
	First         bool                   `protobuf:"varint,6,opt,name=first,proto3" json:"first,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Locator) Reset() {
	*x = Locator{}
	mi := &file_biloba_v1_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Locator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locator) ProtoMessage() {}

func (x *Locator) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locator.ProtoReflect.Descriptor instead.
func (*Locator) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{7}
}

func (x *Locator) GetKind() LocatorKind {
	if x != nil {
		return x.Kind
	}
	return LocatorKind_LOCATOR_KIND_UNSPECIFIED
}

func (x *Locator) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Locator) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Locator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Locator) GetMatch() MatchMode {
	if x != nil {
		return x.Match
	}
	return MatchMode_MATCH_MODE_UNSPECIFIED
}

func (x *Locator) GetFirst() bool {
	if x != nil {
		return x.First
	}
	return false
}

type PollPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeoutMs     int64                  `protobuf:"varint,1,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	IntervalMs    int64                  `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollPolicy) Reset() {
	*x = PollPolicy{}
	mi := &file_biloba_v1_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollPolicy) ProtoMessage() {}

func (x *PollPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollPolicy.ProtoReflect.Descriptor instead.
func (*PollPolicy) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{8}
}

func (x *PollPolicy) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *PollPolicy) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type Cookie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Secure        bool                   `protobuf:"varint,5,opt,name=secure,proto3" json:"secure,omitempty"`
	HttpOnly      bool                   `protobuf:"varint,6,opt,name=http_only,json=httpOnly,proto3" json:"http_only,omitempty"`
	ExpiresUnix   float64                `protobuf:"fixed64,7,opt,name=expires_unix,json=expiresUnix,proto3" json:"expires_unix,omitempty"`
	SameSite      string                 `protobuf:"bytes,8,opt,name=same_site,json=sameSite,proto3" json:"same_site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cookie) Reset() {
	*x = Cookie{}
	mi := &file_biloba_v1_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cookie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cookie) ProtoMessage() {}

func (x *Cookie) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cookie.ProtoReflect.Descriptor instead.
func (*Cookie) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{9}
}

func (x *Cookie) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cookie) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Cookie) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Cookie) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Cookie) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *Cookie) GetHttpOnly() bool {
	if x != nil {
		return x.HttpOnly
	}
	return false
}

func (x *Cookie) GetExpiresUnix() float64 {
	if x != nil {
		return x.ExpiresUnix
	}
	return 0
}

func (x *Cookie) GetSameSite() string {
	if x != nil {
		return x.SameSite
	}
	return ""
}

type NavigateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigateRequest) Reset() {
	*x = NavigateRequest{}
	mi := &file_biloba_v1_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigateRequest) ProtoMessage() {}

func (x *NavigateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigateRequest.ProtoReflect.Descriptor instead.
func (*NavigateRequest) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{10}
}

func (x *NavigateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *NavigateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SetCookiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cookies       []*Cookie              `protobuf:"bytes,2,rep,name=cookies,proto3" json:"cookies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCookiesRequest) Reset() {
	*x = SetCookiesRequest{}
	mi := &file_biloba_v1_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCookiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCookiesRequest) ProtoMessage() {}

func (x *SetCookiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCookiesRequest.ProtoReflect.Descriptor instead.
func (*SetCookiesRequest) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{11}
}

func (x *SetCookiesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetCookiesRequest) GetCookies() []*Cookie {
	if x != nil {
		return x.Cookies
	}
	return nil
}

type ClickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Locator       *Locator               `protobuf:"bytes,2,opt,name=locator,proto3" json:"locator,omitempty"`
	Poll          *PollPolicy            `protobuf:"bytes,3,opt,name=poll,proto3" json:"poll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickRequest) Reset() {
	*x = ClickRequest{}
	mi := &file_biloba_v1_driver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickRequest) ProtoMessage() {}

func (x *ClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickRequest.ProtoReflect.Descriptor instead.
func (*ClickRequest) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{12}
}

func (x *ClickRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClickRequest) GetLocator() *Locator {
	if x != nil {
		return x.Locator
	}
	return nil
}

func (x *ClickRequest) GetPoll() *PollPolicy {
	if x != nil {
		return x.Poll
	}
	return nil
}

type SetValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Locator       *Locator               `protobuf:"bytes,2,opt,name=locator,proto3" json:"locator,omitempty"`
	ValueJson     string                 `protobuf:"bytes,3,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	Poll          *PollPolicy            `protobuf:"bytes,4,opt,name=poll,proto3" json:"poll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValueRequest) Reset() {
	*x = SetValueRequest{}
	mi := &file_biloba_v1_driver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueRequest) ProtoMessage() {}

func (x *SetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueRequest.ProtoReflect.Descriptor instead.
func (*SetValueRequest) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{13}
}

func (x *SetValueRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetValueRequest) GetLocator() *Locator {
	if x != nil {
		return x.Locator
	}
	return nil
}

func (x *SetValueRequest) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

func (x *SetValueRequest) GetPoll() *PollPolicy {
	if x != nil {
		return x.Poll
	}
	return nil
}

type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Expression    string                 `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_biloba_v1_driver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{14}
}

func (x *EvaluateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EvaluateRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *EvaluateRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

type Assertion struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           Assertion_Kind         `protobuf:"varint,1,opt,name=kind,proto3,enum=biloba.v1.Assertion_Kind" json:"kind,omitempty"`
	Locator        *Locator               `protobuf:"bytes,2,opt,name=locator,proto3" json:"locator,omitempty"`
	Attribute      string                 `protobuf:"bytes,3,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Expression     string                 `protobuf:"bytes,4,opt,name=expression,proto3" json:"expression,omitempty"`
	ExpectedString string                 `protobuf:"bytes,5,opt,name=expected_string,json=expectedString,proto3" json:"expected_string,omitempty"`
	ExpectedCount  int64                  `protobuf:"varint,6,opt,name=expected_count,json=expectedCount,proto3" json:"expected_count,omitempty"`
	ExpectedJson   string                 `protobuf:"bytes,7,opt,name=expected_json,json=expectedJson,proto3" json:"expected_json,omitempty"`
	Match          MatchMode              `protobuf:"varint,8,opt,name=match,proto3,enum=biloba.v1.MatchMode" json:"match,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Assertion) Reset() {
	*x = Assertion{}
	mi := &file_biloba_v1_driver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assertion) ProtoMessage() {}

func (x *Assertion) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assertion.ProtoReflect.Descriptor instead.
func (*Assertion) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{15}
}

func (x *Assertion) GetKind() Assertion_Kind {
	if x != nil {
		return x.Kind
	}
	return Assertion_KIND_UNSPECIFIED
}

func (x *Assertion) GetLocator() *Locator {
	if x != nil {
		return x.Locator
	}
	return nil
}

func (x *Assertion) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *Assertion) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *Assertion) GetExpectedString() string {
	if x != nil {
		return x.ExpectedString
	}
	return ""
}

func (x *Assertion) GetExpectedCount() int64 {
	if x != nil {
		return x.ExpectedCount
	}
	return 0
}

func (x *Assertion) GetExpectedJson() string {
	if x != nil {
		return x.ExpectedJson
	}
	return ""
}

func (x *Assertion) GetMatch() MatchMode {
	if x != nil {
		return x.Match
	}
	return MatchMode_MATCH_MODE_UNSPECIFIED
}

type AssertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Assertion     *Assertion             `protobuf:"bytes,2,opt,name=assertion,proto3" json:"assertion,omitempty"`
	Poll          *PollPolicy            `protobuf:"bytes,3,opt,name=poll,proto3" json:"poll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertRequest) Reset() {
	*x = AssertRequest{}
	mi := &file_biloba_v1_driver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertRequest) ProtoMessage() {}

func (x *AssertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertRequest.ProtoReflect.Descriptor instead.
func (*AssertRequest) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{16}
}

func (x *AssertRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AssertRequest) GetAssertion() *Assertion {
	if x != nil {
		return x.Assertion
	}
	return nil
}

func (x *AssertRequest) GetPoll() *PollPolicy {
	if x != nil {
		return x.Poll
	}
	return nil
}

type PollObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       uint32                 `protobuf:"varint,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	ElapsedMs     int64                  `protobuf:"varint,2,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	ObservedJson  string                 `protobuf:"bytes,3,opt,name=observed_json,json=observedJson,proto3" json:"observed_json,omitempty"`
	RetryReason   string                 `protobuf:"bytes,4,opt,name=retry_reason,json=retryReason,proto3" json:"retry_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollObservation) Reset() {
	*x = PollObservation{}
	mi := &file_biloba_v1_driver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollObservation) ProtoMessage() {}

func (x *PollObservation) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollObservation.ProtoReflect.Descriptor instead.
func (*PollObservation) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{17}
}

func (x *PollObservation) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *PollObservation) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *PollObservation) GetObservedJson() string {
	if x != nil {
		return x.ObservedJson
	}
	return ""
}

func (x *PollObservation) GetRetryReason() string {
	if x != nil {
		return x.RetryReason
	}
	return ""
}

type Timings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartedUnixMs int64                  `protobuf:"varint,1,opt,name=started_unix_ms,json=startedUnixMs,proto3" json:"started_unix_ms,omitempty"`
	ElapsedMs     int64                  `protobuf:"varint,2,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timings) Reset() {
	*x = Timings{}
	mi := &file_biloba_v1_driver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timings) ProtoMessage() {}

func (x *Timings) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timings.ProtoReflect.Descriptor instead.
func (*Timings) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{18}
}

func (x *Timings) GetStartedUnixMs() int64 {
	if x != nil {
		return x.StartedUnixMs
	}
	return 0
}

func (x *Timings) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

type Diagnostics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Locator        string                 `protobuf:"bytes,1,opt,name=locator,proto3" json:"locator,omitempty"`
	Expected       string                 `protobuf:"bytes,2,opt,name=expected,proto3" json:"expected,omitempty"`
	DomOutline     string                 `protobuf:"bytes,3,opt,name=dom_outline,json=domOutline,proto3" json:"dom_outline,omitempty"`
	ScreenshotPath string                 `protobuf:"bytes,4,opt,name=screenshot_path,json=screenshotPath,proto3" json:"screenshot_path,omitempty"`
	DaemonDetail   string                 `protobuf:"bytes,5,opt,name=daemon_detail,json=daemonDetail,proto3" json:"daemon_detail,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Diagnostics) Reset() {
	*x = Diagnostics{}
	mi := &file_biloba_v1_driver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostics) ProtoMessage() {}

func (x *Diagnostics) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostics.ProtoReflect.Descriptor instead.
func (*Diagnostics) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{19}
}

func (x *Diagnostics) GetLocator() string {
	if x != nil {
		return x.Locator
	}
	return ""
}

func (x *Diagnostics) GetExpected() string {
	if x != nil {
		return x.Expected
	}
	return ""
}

func (x *Diagnostics) GetDomOutline() string {
	if x != nil {
		return x.DomOutline
	}
	return ""
}

func (x *Diagnostics) GetScreenshotPath() string {
	if x != nil {
		return x.ScreenshotPath
	}
	return ""
}

func (x *Diagnostics) GetDaemonDetail() string {
	if x != nil {
		return x.DaemonDetail
	}
	return ""
}

type OperationResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Matched          bool                   `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	ObservedJson     string                 `protobuf:"bytes,2,opt,name=observed_json,json=observedJson,proto3" json:"observed_json,omitempty"`
	AttemptCount     uint32                 `protobuf:"varint,3,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	Trajectory       []*PollObservation     `protobuf:"bytes,4,rep,name=trajectory,proto3" json:"trajectory,omitempty"`
	Timings          *Timings               `protobuf:"bytes,5,opt,name=timings,proto3" json:"timings,omitempty"`
	Diagnostics      *Diagnostics           `protobuf:"bytes,6,opt,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	RpcRequestCount  uint32                 `protobuf:"varint,7,opt,name=rpc_request_count,json=rpcRequestCount,proto3" json:"rpc_request_count,omitempty"`
	RpcResponseCount uint32                 `protobuf:"varint,8,opt,name=rpc_response_count,json=rpcResponseCount,proto3" json:"rpc_response_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OperationResult) Reset() {
	*x = OperationResult{}
	mi := &file_biloba_v1_driver_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResult) ProtoMessage() {}

func (x *OperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_biloba_v1_driver_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResult.ProtoReflect.Descriptor instead.
func (*OperationResult) Descriptor() ([]byte, []int) {
	return file_biloba_v1_driver_proto_rawDescGZIP(), []int{20}
}

func (x *OperationResult) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *OperationResult) GetObservedJson() string {
	if x != nil {
		return x.ObservedJson
	}
	return ""
}

func (x *OperationResult) GetAttemptCount() uint32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *OperationResult) GetTrajectory() []*PollObservation {
	if x != nil {
		return x.Trajectory
	}
	return nil
}

func (x *OperationResult) GetTimings() *Timings {
	if x != nil {
		return x.Timings
	}
	return nil
}

func (x *OperationResult) GetDiagnostics() *Diagnostics {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *OperationResult) GetRpcRequestCount() uint32 {
	if x != nil {
		return x.RpcRequestCount
	}
	return 0
}

func (x *OperationResult) GetRpcResponseCount() uint32 {
	if x != nil {
		return x.RpcResponseCount
	}
	return 0
}

var File_biloba_v1_driver_proto protoreflect.FileDescriptor

const file_biloba_v1_driver_proto_rawDesc = "" +
	"\n" +
	"\x16biloba/v1/driver.proto\x12\tbiloba.v1\"=\n" +
	"\x10HandshakeRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\"\a\n" +
	"\x05Empty\"b\n" +
	"\x11HandshakeResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\"\x14\n" +
	"\x12OpenSessionRequest\"4\n" +
	"\x13OpenSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"6\n" +
	"\x15PrepareSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xb5\x01\n" +
	"\aLocator\x12*\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x16.biloba.v1.LocatorKindR\x04kind\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12*\n" +
	"\x05match\x18\x05 \x01(\x0e2\x14.biloba.v1.MatchModeR\x05match\x12\x14\n" +
	"\x05first\x18\x06 \x01(\bR\x05first\"L\n" +
	"\n" +
	"PollPolicy\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x01 \x01(\x03R\ttimeoutMs\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\x03R\n" +
	"intervalMs\"\xd3\x01\n" +
	"\x06Cookie\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06secure\x18\x05 \x01(\bR\x06secure\x12\x1b\n" +
	"\thttp_only\x18\x06 \x01(\bR\bhttpOnly\x12!\n" +
	"\fexpires_unix\x18\a \x01(\x01R\vexpiresUnix\x12\x1b\n" +
	"\tsame_site\x18\b \x01(\tR\bsameSite\"B\n" +
	"\x0fNavigateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"_\n" +
	"\x11SetCookiesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12+\n" +
	"\acookies\x18\x02 \x03(\v2\x11.biloba.v1.CookieR\acookies\"\x86\x01\n" +
	"\fClickRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12,\n" +
	"\alocator\x18\x02 \x01(\v2\x12.biloba.v1.LocatorR\alocator\x12)\n" +
	"\x04poll\x18\x03 \x01(\v2\x15.biloba.v1.PollPolicyR\x04poll\"\xa8\x01\n" +
	"\x0fSetValueRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12,\n" +
	"\alocator\x18\x02 \x01(\v2\x12.biloba.v1.LocatorR\alocator\x12\x1d\n" +
	"\n" +
	"value_json\x18\x03 \x01(\tR\tvalueJson\x12)\n" +
	"\x04poll\x18\x04 \x01(\v2\x15.biloba.v1.PollPolicyR\x04poll\"w\n" +
	"\x0fEvaluateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\"\xb8\x03\n" +
	"\tAssertion\x12-\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x19.biloba.v1.Assertion.KindR\x04kind\x12,\n" +
	"\alocator\x18\x02 \x01(\v2\x12.biloba.v1.LocatorR\alocator\x12\x1c\n" +
	"\tattribute\x18\x03 \x01(\tR\tattribute\x12\x1e\n" +
	"\n" +
	"expression\x18\x04 \x01(\tR\n" +
	"expression\x12'\n" +
	"\x0fexpected_string\x18\x05 \x01(\tR\x0eexpectedString\x12%\n" +
	"\x0eexpected_count\x18\x06 \x01(\x03R\rexpectedCount\x12#\n" +
	"\rexpected_json\x18\a \x01(\tR\fexpectedJson\x12*\n" +
	"\x05match\x18\b \x01(\x0e2\x14.biloba.v1.MatchModeR\x05match\"o\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aVISIBLE\x10\x01\x12\b\n" +
	"\x04TEXT\x10\x02\x12\t\n" +
	"\x05COUNT\x10\x03\x12\r\n" +
	"\tATTRIBUTE\x10\x04\x12\t\n" +
	"\x05VALUE\x10\x05\x12\a\n" +
	"\x03URL\x10\x06\x12\f\n" +
	"\bEVALUATE\x10\a\"\x8d\x01\n" +
	"\rAssertRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x122\n" +
	"\tassertion\x18\x02 \x01(\v2\x14.biloba.v1.AssertionR\tassertion\x12)\n" +
	"\x04poll\x18\x03 \x01(\v2\x15.biloba.v1.PollPolicyR\x04poll\"\x92\x01\n" +
	"\x0fPollObservation\x12\x18\n" +
	"\aattempt\x18\x01 \x01(\rR\aattempt\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x02 \x01(\x03R\telapsedMs\x12#\n" +
	"\robserved_json\x18\x03 \x01(\tR\fobservedJson\x12!\n" +
	"\fretry_reason\x18\x04 \x01(\tR\vretryReason\"P\n" +
	"\aTimings\x12&\n" +
	"\x0fstarted_unix_ms\x18\x01 \x01(\x03R\rstartedUnixMs\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x02 \x01(\x03R\telapsedMs\"\xb2\x01\n" +
	"\vDiagnostics\x12\x18\n" +
	"\alocator\x18\x01 \x01(\tR\alocator\x12\x1a\n" +
	"\bexpected\x18\x02 \x01(\tR\bexpected\x12\x1f\n" +
	"\vdom_outline\x18\x03 \x01(\tR\n" +
	"domOutline\x12'\n" +
	"\x0fscreenshot_path\x18\x04 \x01(\tR\x0escreenshotPath\x12#\n" +
	"\rdaemon_detail\x18\x05 \x01(\tR\fdaemonDetail\"\xf3\x02\n" +
	"\x0fOperationResult\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched\x12#\n" +
	"\robserved_json\x18\x02 \x01(\tR\fobservedJson\x12#\n" +
	"\rattempt_count\x18\x03 \x01(\rR\fattemptCount\x12:\n" +
	"\n" +
	"trajectory\x18\x04 \x03(\v2\x1a.biloba.v1.PollObservationR\n" +
	"trajectory\x12,\n" +
	"\atimings\x18\x05 \x01(\v2\x12.biloba.v1.TimingsR\atimings\x128\n" +
	"\vdiagnostics\x18\x06 \x01(\v2\x16.biloba.v1.DiagnosticsR\vdiagnostics\x12*\n" +
	"\x11rpc_request_count\x18\a \x01(\rR\x0frpcRequestCount\x12,\n" +
	"\x12rpc_response_count\x18\b \x01(\rR\x10rpcResponseCount*U\n" +
	"\vLocatorKind\x12\x1c\n" +
	"\x18LOCATOR_KIND_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03CSS\x10\x01\x12\v\n" +
	"\aTEST_ID\x10\x02\x12\b\n" +
	"\x04TEXT\x10\x03\x12\b\n" +
	"\x04ROLE\x10\x04*@\n" +
	"\tMatchMode\x12\x1a\n" +
	"\x16MATCH_MODE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05EXACT\x10\x01\x12\f\n" +
	"\bCONTAINS\x10\x022\xbe\x05\n" +
	"\fBilobaDriver\x12F\n" +
	"\tHandshake\x12\x1b.biloba.v1.HandshakeRequest\x1a\x1c.biloba.v1.HandshakeResponse\x12L\n" +
	"\vOpenSession\x12\x1d.biloba.v1.OpenSessionRequest\x1a\x1e.biloba.v1.OpenSessionResponse\x12D\n" +
	"\x0ePrepareSession\x12 .biloba.v1.PrepareSessionRequest\x1a\x10.biloba.v1.Empty\x12@\n" +
	"\fCloseSession\x12\x1e.biloba.v1.CloseSessionRequest\x1a\x10.biloba.v1.Empty\x12B\n" +
	"\bNavigate\x12\x1a.biloba.v1.NavigateRequest\x1a\x1a.biloba.v1.OperationResult\x12F\n" +
	"\n" +
	"SetCookies\x12\x1c.biloba.v1.SetCookiesRequest\x1a\x1a.biloba.v1.OperationResult\x12<\n" +
	"\x05Click\x12\x17.biloba.v1.ClickRequest\x1a\x1a.biloba.v1.OperationResult\x12B\n" +
	"\bSetValue\x12\x1a.biloba.v1.SetValueRequest\x1a\x1a.biloba.v1.OperationResult\x12B\n" +
	"\bEvaluate\x12\x1a.biloba.v1.EvaluateRequest\x1a\x1a.biloba.v1.OperationResult\x12>\n" +
	"\x06Assert\x12\x18.biloba.v1.AssertRequest\x1a\x1a.biloba.v1.OperationResultB<Z:github.com/onsi/biloba/protocol/internal/bilobav1;bilobav1b\x06proto3"

var (
	file_biloba_v1_driver_proto_rawDescOnce sync.Once
	file_biloba_v1_driver_proto_rawDescData []byte
)

func file_biloba_v1_driver_proto_rawDescGZIP() []byte {
	file_biloba_v1_driver_proto_rawDescOnce.Do(func() {
		file_biloba_v1_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_biloba_v1_driver_proto_rawDesc), len(file_biloba_v1_driver_proto_rawDesc)))
	})
	return file_biloba_v1_driver_proto_rawDescData
}

var file_biloba_v1_driver_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_biloba_v1_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_biloba_v1_driver_proto_goTypes = []any{
	(LocatorKind)(0),              // 0: biloba.v1.LocatorKind
	(MatchMode)(0),                // 1: biloba.v1.MatchMode
	(Assertion_Kind)(0),           // 2: biloba.v1.Assertion.Kind
	(*HandshakeRequest)(nil),      // 3: biloba.v1.HandshakeRequest
	(*Empty)(nil),                 // 4: biloba.v1.Empty
	(*HandshakeResponse)(nil),     // 5: biloba.v1.HandshakeResponse
	(*OpenSessionRequest)(nil),    // 6: biloba.v1.OpenSessionRequest
	(*OpenSessionResponse)(nil),   // 7: biloba.v1.OpenSessionResponse
	(*PrepareSessionRequest)(nil), // 8: biloba.v1.PrepareSessionRequest
	(*CloseSessionRequest)(nil),   // 9: biloba.v1.CloseSessionRequest
	(*Locator)(nil),               // 10: biloba.v1.Locator
	(*PollPolicy)(nil),            // 11: biloba.v1.PollPolicy
	(*Cookie)(nil),                // 12: biloba.v1.Cookie
	(*NavigateRequest)(nil),       // 13: biloba.v1.NavigateRequest
	(*SetCookiesRequest)(nil),     // 14: biloba.v1.SetCookiesRequest
	(*ClickRequest)(nil),          // 15: biloba.v1.ClickRequest
	(*SetValueRequest)(nil),       // 16: biloba.v1.SetValueRequest
	(*EvaluateRequest)(nil),       // 17: biloba.v1.EvaluateRequest
	(*Assertion)(nil),             // 18: biloba.v1.Assertion
	(*AssertRequest)(nil),         // 19: biloba.v1.AssertRequest
	(*PollObservation)(nil),       // 20: biloba.v1.PollObservation
	(*Timings)(nil),               // 21: biloba.v1.Timings
	(*Diagnostics)(nil),           // 22: biloba.v1.Diagnostics
	(*OperationResult)(nil),       // 23: biloba.v1.OperationResult
}
var file_biloba_v1_driver_proto_depIdxs = []int32{
	0,  // 0: biloba.v1.Locator.kind:type_name -> biloba.v1.LocatorKind
	1,  // 1: biloba.v1.Locator.match:type_name -> biloba.v1.MatchMode
	12, // 2: biloba.v1.SetCookiesRequest.cookies:type_name -> biloba.v1.Cookie
	10, // 3: biloba.v1.ClickRequest.locator:type_name -> biloba.v1.Locator
	11, // 4: biloba.v1.ClickRequest.poll:type_name -> biloba.v1.PollPolicy
	10, // 5: biloba.v1.SetValueRequest.locator:type_name -> biloba.v1.Locator
	11, // 6: biloba.v1.SetValueRequest.poll:type_name -> biloba.v1.PollPolicy
	2,  // 7: biloba.v1.Assertion.kind:type_name -> biloba.v1.Assertion.Kind
	10, // 8: biloba.v1.Assertion.locator:type_name -> biloba.v1.Locator
	1,  // 9: biloba.v1.Assertion.match:type_name -> biloba.v1.MatchMode
	18, // 10: biloba.v1.AssertRequest.assertion:type_name -> biloba.v1.Assertion
	11, // 11: biloba.v1.AssertRequest.poll:type_name -> biloba.v1.PollPolicy
	20, // 12: biloba.v1.OperationResult.trajectory:type_name -> biloba.v1.PollObservation
	21, // 13: biloba.v1.OperationResult.timings:type_name -> biloba.v1.Timings
	22, // 14: biloba.v1.OperationResult.diagnostics:type_name -> biloba.v1.Diagnostics
	3,  // 15: biloba.v1.BilobaDriver.Handshake:input_type -> biloba.v1.HandshakeRequest
	6,  // 16: biloba.v1.BilobaDriver.OpenSession:input_type -> biloba.v1.OpenSessionRequest
	8,  // 17: biloba.v1.BilobaDriver.PrepareSession:input_type -> biloba.v1.PrepareSessionRequest
	9,  // 18: biloba.v1.BilobaDriver.CloseSession:input_type -> biloba.v1.CloseSessionRequest
	13, // 19: biloba.v1.BilobaDriver.Navigate:input_type -> biloba.v1.NavigateRequest
	14, // 20: biloba.v1.BilobaDriver.SetCookies:input_type -> biloba.v1.SetCookiesRequest
	15, // 21: biloba.v1.BilobaDriver.Click:input_type -> biloba.v1.ClickRequest
	16, // 22: biloba.v1.BilobaDriver.SetValue:input_type -> biloba.v1.SetValueRequest
	17, // 23: biloba.v1.BilobaDriver.Evaluate:input_type -> biloba.v1.EvaluateRequest
	19, // 24: biloba.v1.BilobaDriver.Assert:input_type -> biloba.v1.AssertRequest
	5,  // 25: biloba.v1.BilobaDriver.Handshake:output_type -> biloba.v1.HandshakeResponse
	7,  // 26: biloba.v1.BilobaDriver.OpenSession:output_type -> biloba.v1.OpenSessionResponse
	4,  // 27: biloba.v1.BilobaDriver.PrepareSession:output_type -> biloba.v1.Empty
	4,  // 28: biloba.v1.BilobaDriver.CloseSession:output_type -> biloba.v1.Empty
	23, // 29: biloba.v1.BilobaDriver.Navigate:output_type -> biloba.v1.OperationResult
	23, // 30: biloba.v1.BilobaDriver.SetCookies:output_type -> biloba.v1.OperationResult
	23, // 31: biloba.v1.BilobaDriver.Click:output_type -> biloba.v1.OperationResult
	23, // 32: biloba.v1.BilobaDriver.SetValue:output_type -> biloba.v1.OperationResult
	23, // 33: biloba.v1.BilobaDriver.Evaluate:output_type -> biloba.v1.OperationResult
	23, // 34: biloba.v1.BilobaDriver.Assert:output_type -> biloba.v1.OperationResult
	25, // [25:35] is the sub-list for method output_type
	15, // [15:25] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_biloba_v1_driver_proto_init() }
func file_biloba_v1_driver_proto_init() {
	if File_biloba_v1_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_biloba_v1_driver_proto_rawDesc), len(file_biloba_v1_driver_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_biloba_v1_driver_proto_goTypes,
		DependencyIndexes: file_biloba_v1_driver_proto_depIdxs,
		EnumInfos:         file_biloba_v1_driver_proto_enumTypes,
		MessageInfos:      file_biloba_v1_driver_proto_msgTypes,
	}.Build()
	File_biloba_v1_driver_proto = out.File
	file_biloba_v1_driver_proto_goTypes = nil
	file_biloba_v1_driver_proto_depIdxs = nil
}
