// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: biloba/v1/driver.proto

package bilobav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BilobaDriver_Handshake_FullMethodName      = "/biloba.v1.BilobaDriver/Handshake"
	BilobaDriver_OpenSession_FullMethodName    = "/biloba.v1.BilobaDriver/OpenSession"
	BilobaDriver_PrepareSession_FullMethodName = "/biloba.v1.BilobaDriver/PrepareSession"
	BilobaDriver_CloseSession_FullMethodName   = "/biloba.v1.BilobaDriver/CloseSession"
	BilobaDriver_Navigate_FullMethodName       = "/biloba.v1.BilobaDriver/Navigate"
	BilobaDriver_SetCookies_FullMethodName     = "/biloba.v1.BilobaDriver/SetCookies"
	BilobaDriver_Click_FullMethodName          = "/biloba.v1.BilobaDriver/Click"
	BilobaDriver_SetValue_FullMethodName       = "/biloba.v1.BilobaDriver/SetValue"
	BilobaDriver_Evaluate_FullMethodName       = "/biloba.v1.BilobaDriver/Evaluate"
	BilobaDriver_Assert_FullMethodName         = "/biloba.v1.BilobaDriver/Assert"
)

// BilobaDriverClient is the client API for BilobaDriver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BilobaDriverClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error)
	PrepareSession(ctx context.Context, in *PrepareSessionRequest, opts ...grpc.CallOption) (*Empty, error)
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*Empty, error)
	Navigate(ctx context.Context, in *NavigateRequest, opts ...grpc.CallOption) (*OperationResult, error)
	SetCookies(ctx context.Context, in *SetCookiesRequest, opts ...grpc.CallOption) (*OperationResult, error)
	Click(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*OperationResult, error)
	SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*OperationResult, error)
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*OperationResult, error)
	Assert(ctx context.Context, in *AssertRequest, opts ...grpc.CallOption) (*OperationResult, error)
}

type bilobaDriverClient struct {
	cc grpc.ClientConnInterface
}

func NewBilobaDriverClient(cc grpc.ClientConnInterface) BilobaDriverClient {
	return &bilobaDriverClient{cc}
}

func (c *bilobaDriverClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, BilobaDriver_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bilobaDriverClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenSessionResponse)
	err := c.cc.Invoke(ctx, BilobaDriver_OpenSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bilobaDriverClient) PrepareSession(ctx context.Context, in *PrepareSessionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, BilobaDriver_PrepareSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bilobaDriverClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, BilobaDriver_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bilobaDriverClient) Navigate(ctx context.Context, in *NavigateRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, BilobaDriver_Navigate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bilobaDriverClient) SetCookies(ctx context.Context, in *SetCookiesRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, BilobaDriver_SetCookies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bilobaDriverClient) Click(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, BilobaDriver_Click_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bilobaDriverClient) SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, BilobaDriver_SetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bilobaDriverClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, BilobaDriver_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bilobaDriverClient) Assert(ctx context.Context, in *AssertRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, BilobaDriver_Assert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BilobaDriverServer is the server API for BilobaDriver service.
// All implementations must embed UnimplementedBilobaDriverServer
// for forward compatibility.
type BilobaDriverServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error)
	PrepareSession(context.Context, *PrepareSessionRequest) (*Empty, error)
	CloseSession(context.Context, *CloseSessionRequest) (*Empty, error)
	Navigate(context.Context, *NavigateRequest) (*OperationResult, error)
	SetCookies(context.Context, *SetCookiesRequest) (*OperationResult, error)
	Click(context.Context, *ClickRequest) (*OperationResult, error)
	SetValue(context.Context, *SetValueRequest) (*OperationResult, error)
	Evaluate(context.Context, *EvaluateRequest) (*OperationResult, error)
	Assert(context.Context, *AssertRequest) (*OperationResult, error)
	mustEmbedUnimplementedBilobaDriverServer()
}

// UnimplementedBilobaDriverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBilobaDriverServer struct{}

func (UnimplementedBilobaDriverServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedBilobaDriverServer) OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedBilobaDriverServer) PrepareSession(context.Context, *PrepareSessionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareSession not implemented")
}
func (UnimplementedBilobaDriverServer) CloseSession(context.Context, *CloseSessionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedBilobaDriverServer) Navigate(context.Context, *NavigateRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Navigate not implemented")
}
func (UnimplementedBilobaDriverServer) SetCookies(context.Context, *SetCookiesRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCookies not implemented")
}
func (UnimplementedBilobaDriverServer) Click(context.Context, *ClickRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Click not implemented")
}
func (UnimplementedBilobaDriverServer) SetValue(context.Context, *SetValueRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValue not implemented")
}
func (UnimplementedBilobaDriverServer) Evaluate(context.Context, *EvaluateRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedBilobaDriverServer) Assert(context.Context, *AssertRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Assert not implemented")
}
func (UnimplementedBilobaDriverServer) mustEmbedUnimplementedBilobaDriverServer() {}
func (UnimplementedBilobaDriverServer) testEmbeddedByValue()                      {}

// UnsafeBilobaDriverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BilobaDriverServer will
// result in compilation errors.
type UnsafeBilobaDriverServer interface {
	mustEmbedUnimplementedBilobaDriverServer()
}

func RegisterBilobaDriverServer(s grpc.ServiceRegistrar, srv BilobaDriverServer) {
	// If the following call pancis, it indicates UnimplementedBilobaDriverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BilobaDriver_ServiceDesc, srv)
}

func _BilobaDriver_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BilobaDriverServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BilobaDriver_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BilobaDriverServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BilobaDriver_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BilobaDriverServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BilobaDriver_OpenSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BilobaDriverServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BilobaDriver_PrepareSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BilobaDriverServer).PrepareSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BilobaDriver_PrepareSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BilobaDriverServer).PrepareSession(ctx, req.(*PrepareSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BilobaDriver_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BilobaDriverServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BilobaDriver_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BilobaDriverServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BilobaDriver_Navigate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NavigateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BilobaDriverServer).Navigate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BilobaDriver_Navigate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BilobaDriverServer).Navigate(ctx, req.(*NavigateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BilobaDriver_SetCookies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCookiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BilobaDriverServer).SetCookies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BilobaDriver_SetCookies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BilobaDriverServer).SetCookies(ctx, req.(*SetCookiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BilobaDriver_Click_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BilobaDriverServer).Click(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BilobaDriver_Click_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BilobaDriverServer).Click(ctx, req.(*ClickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BilobaDriver_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BilobaDriverServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BilobaDriver_SetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BilobaDriverServer).SetValue(ctx, req.(*SetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BilobaDriver_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BilobaDriverServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BilobaDriver_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BilobaDriverServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BilobaDriver_Assert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BilobaDriverServer).Assert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BilobaDriver_Assert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BilobaDriverServer).Assert(ctx, req.(*AssertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BilobaDriver_ServiceDesc is the grpc.ServiceDesc for BilobaDriver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BilobaDriver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "biloba.v1.BilobaDriver",
	HandlerType: (*BilobaDriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _BilobaDriver_Handshake_Handler,
		},
		{
			MethodName: "OpenSession",
			Handler:    _BilobaDriver_OpenSession_Handler,
		},
		{
			MethodName: "PrepareSession",
			Handler:    _BilobaDriver_PrepareSession_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _BilobaDriver_CloseSession_Handler,
		},
		{
			MethodName: "Navigate",
			Handler:    _BilobaDriver_Navigate_Handler,
		},
		{
			MethodName: "SetCookies",
			Handler:    _BilobaDriver_SetCookies_Handler,
		},
		{
			MethodName: "Click",
			Handler:    _BilobaDriver_Click_Handler,
		},
		{
			MethodName: "SetValue",
			Handler:    _BilobaDriver_SetValue_Handler,
		},
		{
			MethodName: "Evaluate",
			Handler:    _BilobaDriver_Evaluate_Handler,
		},
		{
			MethodName: "Assert",
			Handler:    _BilobaDriver_Assert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "biloba/v1/driver.proto",
}
